# Generated by Django 6.1.1 on 2026-09-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=20, unique=True)),
                ('team_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_phone', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=100)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('user_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.registration')),
            ],
        ),
    ]
